Initial commit
SiMDE-Projects/emploidut-api pull request #2
Opened 2021-03-05 15:14 UTC by victor-tndl

2021-03-06 22:35 UTC, cesar-richard requested changes
T'as un bon initial commit la , pas mal. 
Je te laisse quelques commentaires pour que tu puisses sortir quelque chose de plus propre comme base mais évidemment c'est de l'initial donc on se prend pas la tête ^^

2021-03-06 22:35 UTC, cesar-richard commented on routes/index.ts
> +router.get('/emploiDuTemps', function(req?: any, res?: any, next?: any) {
attention aux url avec de la casse. Ca peut vite s'avérer casse-couilles (ptdr jem lumour)

2021-03-06 22:35 UTC, cesar-richard commented on routes/index.ts
> +router.get('/timeSlots', TimeSlotController.getTimeSlots)
casse

2021-03-06 22:35 UTC, cesar-richard commented on routes/index.ts
> +router.post('/timeSlots', TimeSlotController.postTimeSlots)
casse

2021-03-06 22:35 UTC, cesar-richard commented on routes/index.ts
> +router.put('/timeSlots', TimeSlotController.putTimeSlots)
casse

2021-03-06 22:35 UTC, cesar-richard commented on routes/index.ts
> +**********************************************************************/
Dans l'ensemble il est plus commun de regrouper par endpoint et de mettre les differentes Methods ensemble plutot que grouper par method et de lister les endpoints comme tu as fait :)

2021-03-06 22:35 UTC, cesar-richard commented on routes/users.ts
> +  res.send('respond with a resource');
Haha, drole mais a pas oublier de virer ^^

2021-03-06 22:35 UTC, cesar-richard commented on src/model/Server.ts
> +const port = 3000;
Il faudrait que tu tires cette information d'une variable d'environnement pour faire bien.
`const port = process.env.PORT || 3000;` fait le taff ^^

2021-03-06 22:35 UTC, cesar-richard commented on src/model/Server.ts
> +        app.use(logger('dev'));
`app.use(logger(process.env.NODE_ENV || 'dev'));`
Et c'est toi qui a choisi 'dev' ? On peut mettre 'developpement' a la place ?

2021-03-07 11:31 UTC, victor-tndl commented on src/model/Server.ts
> +        app.use(logger('dev'));
C'est la configuration de base avec expressJs, si je le change faudrait redéfinir un logger je pense.

2021-03-07 12:04 UTC, cesar-richard commented on src/model/Server.ts
> +        app.use(logger('dev'));
D'acc, je m'en doutais un peu d'où ma question ^^ 
Roule si c'est la config par def ce devrait sauter au build de prod, je verifierais ca quand on fera la config CI :)

2021-03-07 12:06 UTC, cesar-richard approved these changes

2021-03-07 12:06 UTC, cesar-richard commented on package.json
> +    "dotenv": "^8.2.0",
Moyen convaincu de le passer ici plutot quand dans les devDeps. Mais on va garder ca dans un premier temps :)

2021-03-07 13:38 UTC, victor-tndl commented on package.json
> +    "dotenv": "^8.2.0",
En effet j'ai oublié un argument quand je l'ai add, je le changerai dans la prochaine PR

2021-03-07 13:41 UTC, merged